
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Aug 04 12:29:17 VET 2014
//----------------------------------------------------

package paquete;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int UNI = 23;
  public static final int AND = 20;
  public static final int MENOR = 15;
  public static final int PUNTO = 8;
  public static final int CADENA = 3;
  public static final int INT = 25;
  public static final int OR = 19;
  public static final int MENORIGUAL = 13;
  public static final int SUMA = 9;
  public static final int DIVI = 11;
  public static final int NOT = 21;
  public static final int MULTI = 10;
  public static final int PRO = 26;
  public static final int COMA = 7;
  public static final int MAYOR = 16;
  public static final int EOF = 0;
  public static final int DIFERENTE = 17;
  public static final int COMILLA = 28;
  public static final int FECHA = 4;
  public static final int MAYORIGUAL = 14;
  public static final int error = 1;
  public static final int NUMERO = 2;
  public static final int PROC = 24;
  public static final int EQ = 18;
  public static final int SEL = 27;
  public static final int DPAREN = 6;
  public static final int DIF = 22;
  public static final int IPAREN = 5;
  public static final int RESTA = 12;
}

